dataset:
  x_train: D:/ISIC2018/data/train/Training_Input
  y_train: D:/ISIC2018/data/train/train_groundtruth.csv


  x_valid: D:/ISIC2018/data/valid/valid_input
  y_valid: D:/ISIC2018/data/valid/valid_groundtruth.csv

  x_test: D:/ISIC2018/data/test/Test_Input
  y_test: D:/ISIC2018/data/test/test_groundtruth.csv

chunk: 10

parameter:
  learning_rate : 0.0005
  epochs : 10
  batch_size : 32
